### ISSUE TITLE
Remove Right Floating Bar

### ISSUE THREAD

**Issue by raduconst** [pixelgrade/hive-lite#3]
Trebuie scoasa bara laterala de cu iconitele sociale si search.

## To-dos
- [x] Remove `<div class="toolbar">` Markup
- [x] Remove Menu Registration
- [x] Check for any issues on Mobile
- [x] Remove Black Bar from Left Side
